
spring.application.name=eventpass-backend


spring.datasource.url=jdbc:h2:mem:eventpass
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
# spring.datasource.url=jdbc:h2:file:./data/eventpass
# spring.jpa.hibernate.ddl-auto=update  


app.jwt.secret=EventPass2024SuperSecretKeyThatIsVeryLongAndSecure!!
app.jwt.expiration=86400000


server.port=8070


management.endpoints.web.exposure.include=health,info


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=eventpass2026@gmail.com
spring.mail.password=EventPass@2026
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true